name: ticketavion
description: Un proyecto Flutter para la aplicación de TicketAvion

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  go_router: ^14.2.7
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
