// File generated by FlutterFire CLI.
// ignore_for_file: unused_import
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Verifica que se retorne la configuración adecuada para cada plataforma
    throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
  }
}
